# Generated by Django 4.2.4 on 2023-10-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_categorias_empleado_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='empleado/default_image.jpg', upload_to='empleado'),
        ),
    ]
