# Generated by Django 4.2.4 on 2023-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='empleado/imagen_admin.png', upload_to='empleado'),
        ),
    ]
