# Generated by Django 4.2.4 on 2023-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoriaprod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprod',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
