# Generated by Django 4.2.4 on 2023-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_categoriaprod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprod',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
