# Generated by Django 4.2.4 on 2023-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
