# Generated by Django 4.2.4 on 2023-10-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_alter_nosotros_contenido_alter_nosotros_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='contenido',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
