# Generated by Django 4.2.4 on 2023-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0004_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='imagen',
            field=models.ImageField(default='ubicacion/9318694.jpg', upload_to='ubicacion'),
        ),
    ]
